/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/domains/{domain}/schema/enumerate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Enumerate Domain Schema
     * @description Enumerate all tables/columns for `domain` (FR-001). Calls no LLM
     *     and returns no row-level data, only structural metadata.
     */
    post: operations["enumerate_domain_schema_domains__domain__schema_enumerate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/domains/{domain}/classify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Classify Domain Schema
     * @description Run the classification graph (research.md §9) over `domain`'s
     *     schema: heuristic pass, then conditional LLM-assisted pass
     *     (FR-002, FR-003). Idempotent per schema snapshot — re-running
     *     re-classifies all columns from scratch (contracts/api.md).
     *
     *     Uses the real Anthropic adapter (`anthropic_client.py`) when an API
     *     credential is configured, falling back to `NullLLMClient` otherwise
     *     — every low-confidence column then stays exactly at its heuristic-
     *     pass score, landing in `pending_review` rather than a fabricated
     *     auto-approval. Every persisted column also writes a `classify_*`
     *     `AuditLogEntry` (FR-010), all sharing one `run_id` — the same id
     *     returned to the caller below.
     */
    post: operations["classify_domain_schema_domains__domain__classify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/domains/{domain}/classifications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Domain Classifications
     * @description List `ColumnClassification` records for `domain`, in **any**
     *     status — closes the gap neither `/review-queue` (pending-only) nor
     *     `/policy` (published, no confidence) can answer (contracts/api.md,
     *     T027a). Omit `table`/`column` to list every classified column.
     */
    get: operations["list_domain_classifications_domains__domain__classifications_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/domains/{domain}/review-queue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Review Queue
     * @description List `ColumnClassification` records with `status == "pending_review"`,
     *     including `heuristic_score`, `llm_score`, `confidence`, and
     *     `llm_rationale` as source signals for the reviewer (contracts/api.md).
     */
    get: operations["list_review_queue_domains__domain__review_queue_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/domains/{domain}/review-queue/{column_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve Review Queue Column
     * @description Transition a `pending_review` column to `approved`, admin-only
     *     (contracts/api.md, FR-013, Scenario 8). `require_admin` rejects any
     *     non-admin caller with 403 before this body runs, leaving the
     *     underlying record unchanged (data-model.md State Transitions).
     */
    post: operations["approve_review_queue_column_domains__domain__review_queue__column_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/domains/{domain}/review-queue/{column_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reject Review Queue Column
     * @description Transition a `pending_review` column to `rejected`, admin-only.
     *     Same auth/audit rules as `approve` (contracts/api.md).
     */
    post: operations["reject_review_queue_column_domains__domain__review_queue__column_id__reject_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/domains/{domain}/review-queue/{column_id}/reclassify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reclassify Review Queue Column
     * @description Overwrite a `pending_review` column's classification with an
     *     admin-supplied value, set `source = "human"`, and transition to
     *     `approved`. Same auth/audit rules as `approve` (contracts/api.md).
     */
    post: operations["reclassify_review_queue_column_domains__domain__review_queue__column_id__reclassify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Classification
     * @enum {string}
     */
    Classification:
      "pii_direct" | "pii_indirect" | "sensitive_category" | "business" | "unclassified";
    /**
     * ClassificationSource
     * @enum {string}
     */
    ClassificationSource: "heuristic" | "llm" | "human";
    /**
     * ClassificationStatus
     * @enum {string}
     */
    ClassificationStatus: "auto_approved" | "pending_review" | "approved" | "rejected";
    /**
     * ColumnClassification
     * @description One column's classification record (data-model.md#ColumnClassification).
     */
    ColumnClassification: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Domain */
      domain: string;
      /** Table Name */
      table_name: string;
      /** Column Name */
      column_name: string;
      /** Data Type */
      data_type: string;
      /** Cardinality Ratio */
      cardinality_ratio: number;
      classification: components["schemas"]["Classification"];
      /** Heuristic Score */
      heuristic_score?: number | null;
      /** Llm Score */
      llm_score?: number | null;
      /** Confidence */
      confidence: number;
      source: components["schemas"]["ClassificationSource"];
      status: components["schemas"]["ClassificationStatus"];
      /** Reviewed By */
      reviewed_by?: string | null;
      /** Reviewed At */
      reviewed_at?: string | null;
      /** Llm Rationale */
      llm_rationale?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ReclassifyRequest */
    ReclassifyRequest: {
      classification: components["schemas"]["Classification"];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  enumerate_domain_schema_domains__domain__schema_enumerate_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Steward-Role"?: string | null;
        "X-Steward-Tenant"?: string | null;
      };
      path: {
        domain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  classify_domain_schema_domains__domain__classify_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Steward-Role"?: string | null;
        "X-Steward-Tenant"?: string | null;
      };
      path: {
        domain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_domain_classifications_domains__domain__classifications_get: {
    parameters: {
      query?: {
        table?: string | null;
        column?: string | null;
      };
      header?: {
        "X-Steward-Role"?: string | null;
        "X-Steward-Tenant"?: string | null;
      };
      path: {
        domain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_review_queue_domains__domain__review_queue_get: {
    parameters: {
      query?: never;
      header?: {
        "X-Steward-Role"?: string | null;
        "X-Steward-Tenant"?: string | null;
      };
      path: {
        domain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_review_queue_column_domains__domain__review_queue__column_id__approve_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Steward-Role"?: string | null;
        "X-Steward-Tenant"?: string | null;
      };
      path: {
        column_id: string;
        domain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ColumnClassification"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reject_review_queue_column_domains__domain__review_queue__column_id__reject_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Steward-Role"?: string | null;
        "X-Steward-Tenant"?: string | null;
      };
      path: {
        column_id: string;
        domain: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ColumnClassification"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reclassify_review_queue_column_domains__domain__review_queue__column_id__reclassify_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Steward-Role"?: string | null;
        "X-Steward-Tenant"?: string | null;
      };
      path: {
        column_id: string;
        domain: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReclassifyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ColumnClassification"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
